<?xml version="1.0"?>
<robot name="omni_robot" xmlns:xacro="http://wiki.ros.org/xacro">

  <!-- MATERIAL DEFINITIONS -->
  <material name="white">
    <color rgba="1 1 1 1"/>  <!-- White -->
  </material>
  <material name="copper">
    <color rgba="0.72 0.45 0.20 1"/>  <!-- Copper -->
  </material>

  <!-- BASE LINK (CYLINDER) -->
  <link name="base_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.11" length="0.064"/>  <!-- 220mm dia, 64mm height -->
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.11" length="0.064"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <!-- OMNI WHEEL MACRO -->
  <xacro:macro name="omni_wheel" params="name x y angle">
    <!-- Main Wheel -->
    <link name="${name}">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>  <!-- Wheel rotation -->
        <geometry>
          <cylinder radius="0.032" length="0.02"/>  <!-- 64mm dia, 20mm thick -->
        </geometry>
        <material name="copper"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="0.04" length="0.02"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.15"/>
        <inertia ixx="0.0002" ixy="0" ixz="0" iyy="0.0002" iyz="0" izz="0.0002"/>
      </inertial>
    </link>

    <!-- Joint to Base -->
    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} -0.01" rpy="0 1.5708 ${angle}"/>
      <axis xyz="0 0 1"/>
      <limit effort="10.0" velocity="10.0"/>
      <dynamics damping="0.1" friction="0.01"/>
    </joint>

    <!-- Rollers -->
    <xacro:property name="roller_radius" value="0.006"/>
    <xacro:property name="roller_length" value="0.012"/>
    <xacro:property name="wheel_radius" value="0.04"/>

    <!-- Roller 0: 0°, inside -->
    <link name="${name}_roller_0">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
      </inertial>
    </link>
    <joint name="${name}_roller_0_joint" type="continuous">
      <parent link="${name}"/>
      <child link="${name}_roller_0"/>
      <origin xyz="0 ${wheel_radius} -0.006" rpy="0 1.5708 0"/>
      <axis xyz="0 0 1"/>  <!-- Roller spins around its own axis -->
      <limit effort="0.0" velocity="0.0"/>
      <dynamics damping="0.01" friction="0.01"/>
    </joint>

    <!-- Roller 1: 22.5°, outnside -->
    <link name="${name}_roller_1">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
      </inertial>
    </link>
    <joint name="${name}_roller_1_joint" type="continuous">
      <parent link="${name}"/>
      <child link="${name}_roller_1"/>
      <origin xyz="${wheel_radius * 0.38268} ${wheel_radius * 0.92388} 0.006" rpy="0.3927 1.5708 0"/>
      <axis xyz="0 0 1"/>  <!-- Roller spins around its own axis -->
      <limit effort="0.0" velocity="0.0"/>
      <dynamics damping="0.01" friction="0.01"/>
    </joint>

    <!-- Roller 2: 45°, inside -->
    <link name="${name}_roller_2">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
      </inertial>
    </link>
    <joint name="${name}_roller_2_joint" type="continuous">
      <parent link="${name}"/>
      <child link="${name}_roller_2"/>
      <origin xyz="${wheel_radius * 0.7071} ${wheel_radius * 0.7071} -0.006" rpy="0.7854 1.5708 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="0.0" velocity="0.0"/>
      <dynamics damping="0.01" friction="0.01"/>
    </joint>

    <!-- Roller 3: 67.5°, outside -->
    <link name="${name}_roller_3">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
      </inertial>
    </link>
    <joint name="${name}_roller_3_joint" type="continuous">
      <parent link="${name}"/>
      <child link="${name}_roller_3"/>
      <origin xyz="${wheel_radius * 0.92388} ${wheel_radius * 0.38268} 0.006" rpy="1.1781 1.5708 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="0.0" velocity="0.0"/>
      <dynamics damping="0.01" friction="0.01"/>
    </joint>

    <!-- Roller 4: 90°, inside -->
    <link name="${name}_roller_4">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
      </inertial>
    </link>
    <joint name="${name}_roller_4_joint" type="continuous">
      <parent link="${name}"/>
      <child link="${name}_roller_4"/>
      <origin xyz="${wheel_radius} 0 -0.006" rpy="1.5708 1.5708 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="0.0" velocity="0.0"/>
      <dynamics damping="0.01" friction="0.01"/>
    </joint>

    <!-- Roller 5: 112.5°, outside -->
    <link name="${name}_roller_5">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
      </inertial>
    </link>
    <joint name="${name}_roller_5_joint" type="continuous">
      <parent link="${name}"/>
      <child link="${name}_roller_5"/>
      <origin xyz="${wheel_radius * 0.92388} ${-wheel_radius * 0.38268} 0.006" rpy="1.9635 1.5708 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="0.0" velocity="0.0"/>
      <dynamics damping="0.01" friction="0.01"/>
    </joint>

    <!-- Roller 6: 135°, inside -->
    <link name="${name}_roller_6">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
      </inertial>
    </link>
    <joint name="${name}_roller_6_joint" type="continuous">
      <parent link="${name}"/>
      <child link="${name}_roller_6"/>
      <origin xyz="${wheel_radius * 0.7071} ${-wheel_radius * 0.7071} -0.006" rpy="2.3562 1.5708 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="0.0" velocity="0.0"/>
      <dynamics damping="0.01" friction="0.01"/>
    </joint>

    <!-- Roller 7: 157.5°, outside -->
    <link name="${name}_roller_7">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
      </inertial>
    </link>
    <joint name="${name}_roller_7_joint" type="continuous">
      <parent link="${name}"/>
      <child link="${name}_roller_7"/>
      <origin xyz="${wheel_radius * 0.38268} ${-wheel_radius * 0.92388} 0.006" rpy="2.7489 1.5708 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="0.0" velocity="0.0"/>
      <dynamics damping="0.01" friction="0.01"/>
    </joint>

    <!-- Roller 8: 180°, inside -->
    <link name="${name}_roller_8">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
      </inertial>
    </link>
    <joint name="${name}_roller_8_joint" type="continuous">
      <parent link="${name}"/>
      <child link="${name}_roller_8"/>
      <origin xyz="0 ${-wheel_radius} -0.006" rpy="0 1.5708 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="0.0" velocity="0.0"/>
      <dynamics damping="0.01" friction="0.01"/>
    </joint>

    <!-- Roller 9: 202.5°, outside -->
    <link name="${name}_roller_9">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
      </inertial>
    </link>
    <joint name="${name}_roller_9_joint" type="continuous">
      <parent link="${name}"/>
      <child link="${name}_roller_9"/>
      <origin xyz="${-wheel_radius * 0.38268} ${-wheel_radius * 0.92388} 0.006" rpy="0.3927 1.5708 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="0.0" velocity="0.0"/>
      <dynamics damping="0.01" friction="0.01"/>
    </joint>

    <!-- Roller 10: 225°, inside -->
    <link name="${name}_roller_10">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
      </inertial>
    </link>
    <joint name="${name}_roller_10_joint" type="continuous">
      <parent link="${name}"/>
      <child link="${name}_roller_10"/>
      <origin xyz="${-wheel_radius * 0.7071} ${-wheel_radius * 0.7071} -0.006" rpy="0.7854 1.5708 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="0.0" velocity="0.0"/>
      <dynamics damping="0.01" friction="0.01"/>
    </joint>

    <!-- Roller 11: 247.5°, outside -->
    <link name="${name}_roller_11">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
      </inertial>
    </link>
    <joint name="${name}_roller_11_joint" type="continuous">
      <parent link="${name}"/>
      <child link="${name}_roller_11"/>
      <origin xyz="${-wheel_radius * 0.92388} ${-wheel_radius * 0.38268} 0.006" rpy="1.1781 1.5708 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="0.0" velocity="0.0"/>
      <dynamics damping="0.01" friction="0.01"/>
    </joint>

    <!-- Roller 12: 270°, inside -->
    <link name="${name}_roller_12">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
      </inertial>
    </link>
    <joint name="${name}_roller_12_joint" type="continuous">
      <parent link="${name}"/>
      <child link="${name}_roller_12"/>
      <origin xyz="${-wheel_radius} 0 -0.006" rpy="1.5708 1.5708 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="0.0" velocity="0.0"/>
      <dynamics damping="0.01" friction="0.01"/>
    </joint>

    <!-- Roller 13: 292.5°, outside -->
    <link name="${name}_roller_13">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
      </inertial>
    </link>
    <joint name="${name}_roller_13_joint" type="continuous">
      <parent link="${name}"/>
      <child link="${name}_roller_13"/>
      <origin xyz="${-wheel_radius * 0.92388} ${wheel_radius * 0.38268} 0.006" rpy="1.9635 1.5708 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="0.0" velocity="0.0"/>
      <dynamics damping="0.01" friction="0.01"/>
    </joint>

    <!-- Roller 14: 315°, inside -->
    <link name="${name}_roller_14">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
      </inertial>
    </link>
    <joint name="${name}_roller_14_joint" type="continuous">
      <parent link="${name}"/>
      <child link="${name}_roller_14"/>
      <origin xyz="${-wheel_radius * 0.7071} ${wheel_radius * 0.7071} -0.006" rpy="2.3562 1.5708 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="0.0" velocity="0.0"/>
      <dynamics damping="0.01" friction="0.01"/>
    </joint>

    <!-- Roller 15: 337.5°, outside -->
    <link name="${name}_roller_15">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${roller_radius}" length="${roller_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
      </inertial>
    </link>
    <joint name="${name}_roller_15_joint" type="continuous">
      <parent link="${name}"/>
      <child link="${name}_roller_15"/>
      <origin xyz="${-wheel_radius * 0.38268} ${wheel_radius * 0.92388} 0.006" rpy="2.7489 1.5708 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="0.0" velocity="0.0"/>
      <dynamics damping="0.01" friction="0.01"/>
    </joint>
  </xacro:macro>

  <!-- THREE WHEELS AT 120° INTERVALS -->
  <xacro:omni_wheel name="wheel_0" x="0.125" y="0" angle="0"/>                   <!-- 0° -->
  <xacro:omni_wheel name="wheel_120" x="-0.0625" y="0.10825" angle="2.0944"/>    <!-- 120° -->
  <xacro:omni_wheel name="wheel_240" x="-0.0625" y="-0.10825" angle="-2.0944"/>  <!-- 240° -->

  <!-- WEBOTS SPECIFIC TAGS -->
  <webots>
    <device reference="wheel_0_joint" type="RotationalMotor"/>
    <device reference="wheel_120_joint" type="RotationalMotor"/>
    <device reference="wheel_240_joint" type="RotationalMotor"/>
    <plugin type="omni_1_webots.motor_driver.MotorDriver"/>
  </webots>
</robot>